GET http://localhost:3001/api/notes

###
POST http://localhost:3001/api/notes
content-type: application/json

{
  "content": "sample",
  "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###
POST http://localhost:3001/api/notes
content-type: application/json

{
  "content": "lol",
  "time": "Wed, 21 Oct 2016 18:27:50 GMT"
}